[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
rs_flow = { path = "rs_flow" }

async-trait = "0.1.74"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"