[package]
name = "rs_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.145"
serde_json = "1.0"
async-trait = "0.1.74"


[dev-dependencies]
tokio = { version = "1.35.0", features = ["full"] }
