[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "2"
members = [
    # -- Libraries
    "crates/libs/rs-flow",          # core.
    "crates/libs/rs-flow-macros",   # macros.

    # -- Examples
    "crates/examples/simple-case",
]