[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
rs_flow = { path = "rs_flow" }
rs_flow_macros = { path = "rs_flow_macros" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"